/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algorithm;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
   
    ArrayList list = new ArrayList();
}
